address_to_send: ''
bridge_option: Aptos
coin_to_transfer: USDC
custom_gas_price: false
gas_limit: '3000000'
gas_price: Auto
max_bridge_amount: ''
max_delay_seconds: '0'
min_bridge_amount: ''
min_delay_seconds: '0'
send_all_balance: true
send_to_one_address: false
slippage: '0.5'
source_chain: Polygon
target_chain: Aptos
test_mode: true
