address_to_send: ''
bridge_option: Aptos
coin_to_transfer: USDC
custom_gas_price: false
gas_limit: '4000000'
gas_price: Auto
max_bridge_amount: '20'
max_delay_seconds: '890'
min_bridge_amount: '15'
min_delay_seconds: '550'
send_all_balance: false
send_to_one_address: false
slippage: '0.5'
source_chain: Polygon
target_chain: Aptos
test_mode: false
