address_to_send: ''
bridge_option: CoreDao
custom_gas_price: false
gas_limit: '3000000'
gas_price: Auto
max_bridge_amount: '0.1'
max_delay_seconds: '0'
min_bridge_amount: '0.1'
min_delay_seconds: '0'
send_all_balance: false
send_to_one_address: false
slippage: '0.5'
source_chain: CoreDao
source_coin_to_transfer: USDT
target_chain: BSC
target_coin_to_transfer: USDT
test_mode: true
